# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56117bccf058bc89ce8e462e629d55921e7e2d5409652aea1ee1e71272c6b84f1c1d06c223f648a52246640aea9db200a20cc34cc316310ead8a542869602962

test:
  secret_key_base: d51b086a4da0d06feb2d2c95aa5d1135d7629bbe1b6b9c07edeeb47cd20c13087439b042eebf8d38dc7fb92c826fa1e9eb2d75dba356e2cf848f02042a40e83b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
